---
hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: अपनी खुद की धुन की रचना करना
description: एक अच्छी डोरबेल की झंकार बनाने के लिए Sonic Pi का उपयोग करना
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: संगीत
technologies: ''
site_areas: प्रोजेक्ट
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: अपने पहले स्वर बजाना
  - 
    title: 'चुनौती: झंकार में सुधार करना'
  - 
    title: झंकार को दोहराना
  - 
    title: 'चुनौती: 4 बार दोहराना'
  - 
    title: अपनी झंकार को रिकॉर्ड करना
  - 
    title: 'चुनौती: एक नई धुन की रचना करना'
