---
hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Componha sua própria música
description: Use o Sonic Pi para criar um toque de campainha legal
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: music
technologies: 'sonic pi'
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - title: Introdução
  - title: Toque suas primeiras notas
  - title: 'Desafio: Melhore a harmonia'
  - title: Repita a harmonia
  - title: 'Desafio: Repita 4 vezes'
  - title: Gravando sua harmonia
  - title: 'Desafio: Componha uma nova música'
