---
hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Redacta tu propia melodía
description: Usa Sonic Pi para crear un timbre de puerta genial
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: music
technologies: sonic pi
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Toca tus primeras notas
- title: 'Desafío: Mejorar el timbre'
- title: Repetir el timbre
- title: 'Desafío: Repetir 4 veces'
- title: Grabando tu timbre
  completion: internal
- title: 'Desafío: Compón una nueva melodía'
