---
hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: 나만의 노래 작곡하기
description: Sonic Pi를 사용하여 멋진 초인종 만들기
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: music
technologies: sonic pi
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: 소개
  completion: engaged
- title: 첫 음 연주하기
- title: '도전과제: 벨소리 발전시키기'
- title: 벨소리 반복하기
- title: '도전과제: 4번 반복하기'
- title: 벨소리 녹음하기
  completion: internal
- title: '도전과제: 새로운 음악 작곡하기'
