---
hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Compose ta propre mélodie
description: Utilise Sonic Pi pour créer un sonnette de porte sympa
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: musique
technologies: 'sonic pi'
site_areas: projets
hardware: ''
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: Jouer tes premières notes
  - 
    title: 'Défi : Améliore la sonnerie'
  - 
    title: Répéter la sonnerie
  - 
    title: 'Défi : Répéter 4 fois'
  - 
    title: Enregistrement de ta sonnerie
  - 
    title: 'Défi : Composer une nouvelle mélodie'
